#!/bin/bash
DB_USER='elektromer';
DB_PASSWD='raspberry';

DB_NAME='elektromer';
TABLE='log';

DLMS_READ=$(python3 main.py -S /dev/ttyACM1 2>/dev/null| awk '/Index: 1 Value: 1.1.14.25.0/{getline;getline;print}' | awk '{gsub(/.*Value: |*/,"");print}')

mysql --user=$DB_USER --password=$DB_PASSWD $DB_NAME -e "INSERT INTO $TABLE (\`TYP\`, \`HODNOTA\`) VALUES ('Frekvence', '$DLMS_READ');";
